### ISSUE TITLE
As an end user, I want to be able to choose a workset on which to focus my dashboard so that I can use the dashboard to explore the workset

### ISSUE THREAD

**Issue by cwulfman** [htrc/torchlite-app#14]
HTRC has discussed some pre-existing worksets they imagine would constitute the selection list, but they have not indicated what those worksets are or where information about them can be obtained.

The wireframe features a "select workset" widget with a two-state filter ("all worksets" and "my worksets"), and an (empty) table with "name", "creator", and "description" headings.  Based on conversations with the designers, it seems the intention is to allow the user to review a list of available worksets, both those compiled by HTRC and those the user has compiled elsewhere in the HTRC system. The table should act both as a table and a menu: when the user selects an item from the menu, the dashboard interface should update by showing the name of the selected workset.  

There is no "confirm my choice" button, so there are potential performance issues here: when should the UI convey the user's choice to the backend? Presumably the system should respond to the user's choice of workset by updating the widgets on the dashboard, but that might be an expensive operation.

### Dependencies

- [x] https://github.com/htrc/torchlite-frontend/issues/4
- [x] https://github.com/htrc/torchlite-app/issues/25
- [x] a back-end API end point for setting a dashboard's current workset
- [x] a handler for that end point

**Comment by jswatsch** [comment]
Add another column in table "number of volumes" in the workset in addition to "name", "creator".
HTRC is ok with an "apply" or "confirm" button, and even desirable since it will improve performance
