### ISSUE TITLE
As an end user, I want to be able to use a widget to see the timeline of volume publication in my workset

### ISSUE THREAD

**Issue by cwulfman** [htrc/torchlite-app#16]
The wireframe shows varicolored pills above and below a thin black line will small hatch-marks labeled with dates.  Below the line is a slider with a gray label ("Adjust years on map") and two controls, labeled MIN and MAX.  It looks like this control was copy/pasted from the Map widget.

Presumably each pill is meant to represent a volume; the spacing between the hatch-marks suggests the granularity of the x-axis is a month.

This widget plots the date of publication for all the volumes in a workset on a timeline.

We contracted to produce the widgets iteratively.  The first version of the widget will be static; subsequent versions will include controls of some sort (slliders, perhaps) to let the user change the display.

The wireframe dashboard includes a depiction of what the timeline widget might look like. We will need to work with the Janet and Jenny to understand more fully what this widget is supposed to convey:

- What are the colors supposed to represent?
- Why are some above the line and some below?
- What happens if there many volumes (thousands) to display: how should the visualization scale?
- Dates of book publication are typically expressed in years, not months and years. How should that difference in granularity be handled in the graphic?
- What are the controllers on the slider supposed to do?

### Backend
[x] implement widget back-end

**Comment by jswatsch** [comment]
How is this different than issue #20 ?

**Comment by cwulfman** [comment]
It is an older draft of #20; I am closing it.
