### ISSUE TITLE
As an end user, I want to be able to filter my workset and have the filtered data show up in the widgets

### ISSUE THREAD

**Issue by cwulfman** [htrc/torchlite-app#17]
The wireframe shows a list of eight checkboxes, each corresponding with a property by which the workset should be filtered:

1. Publication Title
2. Publication Date
3. Genre
4. Resource Type
5. Category
6. Contributor
7. Publisher
8. Access Rights
~~8. Availability~~
9. Place of Publication
10. Language
11. Source Institution

We need to confirm with the client what is supposed to happen when each of these buttons is toggled.  What, for example, does it mean to filter by Publication Title? Should the user be presented with a textbox for a regular expression that matches titles?  How should the dashboard indicate that a filter has been successfully applied?

Does the client mean "facet" by these properties?

Dependencies:
- [x] https://github.com/htrc/torchlite-backend/issues/44
- [x] https://github.com/htrc/torchlite-frontend/issues/9

**Comment by jswatsch** [comment]
There should be a "clear filters" button

**Comment by jswatsch** [comment]
Added language and source institution as per [requirements document](https://docs.google.com/document/d/1PfBX4rnLnYMX-7h48C3Qr0_iQM_PAxqn5hOJryPFn80/edit).
