### ISSUE TITLE
As an end user, I want to be able to reproduce widgets in a Jupyter Notebook

### ISSUE THREAD

**Issue by cwulfman** [htrc/torchlite-app#22]

**Comment by jswatsch** [comment]
- Export the widget functions in a Jupyter notebook (including workset selection, filters, data)
- Option to embed the underlying data so the notebook works independently of the API (self-contained and includes the data)

**Comment by cwulfman** [comment]
This can’t be right, Hector: why should I be working on this now? https://github.com/htrc/torchlite-app/issues/22


On May 11, 2023, at 10:27 AM, Hector Gonzalez ***@***.******@***.***>> wrote:



Assigned #22<https://github.com/htrc/torchlite-app/issues/22> to @cwulfman<https://github.com/cwulfman>.
