### ISSUE TITLE
As a HTRC admin, I want to be able to specify a set of pre-defined worksets

### ISSUE THREAD

**Issue by jswatsch** [htrc/torchlite-app#32]
Goal is to have a set of default HTRC-predefined worksets (with filters and settings) available on landing page. Selections can rotate at random (or determined by HTRC, e.g. configurable), so that user sees a different sample workset each time they load the landing page.

Will show default filters for the predefined worksets.

All of the above can be specified in a configuration file loaded at startup by TORCHLITE

### Dependencies

- [x] https://github.com/htrc/torchlite-app/issues/25

**Comment by cwulfman** [comment]
@jswatsch This story introduces a new interface component called _the landing page_. What is it? How is it different from the dashboard?

What do you mean by default filters?

**Comment by jswatsch** [comment]
@cwulfman it's not different than the dashboard. The idea is when a user first navigates to the dashboard, it is preloaded with some data. Does that make sense?

**Comment by cwulfman** [comment]
Yes.  Just making sure.
