### ISSUE TITLE
Dashboard Filters/Faceting Workflow Specifications

### ISSUE THREAD

**Issue by jswatsch** [htrc/torchlite-app#48]
re: filters and facets at the dashboard level (Apply Data Filters section of the dashboard)

- Each field is a dropdown that displays the items for that field in a list
- The dropdown field also lets a user search within that list
- The field lets you add multiple items at once and remove them by clicking and X next to the item
- The other fields dynamically update as you select items in a field. E.g., if you select "in-copyright" for access rights, only in-copyright titles show up in the "Publication title field"
- User clicks "apply filters" to implement their selections
- The widgets update
- User clicks "clear filters" to remove all of their choices
- The widgets update

An example that is a close approximate to what we're describing is how [Bookworm](https://bookworm.htrc.illinois.edu/develop/) handles filtering.

In this screenshot, you can see that when you click on a field, it displays a dropdown list to select from:
![Image](https://github.com/htrc/torchlite-app/assets/108837861/21583e07-b724-4568-bf30-67c3d1736a79)

Here you can see that you are able to search within that list:
![Image](https://github.com/htrc/torchlite-app/assets/108837861/504ba878-8a98-4cc7-a9cb-15d8920ecbc7)

Here you can see multiple items selected and the ability to remove them by clicking the X:
![Image](https://github.com/htrc/torchlite-app/assets/108837861/a0ed982a-97fb-4c5c-ab98-c4950f433f24)

Jenny updated the wireframe: https://sq8xm2.axshare.com/?id=kjydh9&p=home
and created a workflow diagram: https://sq8xm2.axshare.com/?id=yqohbt&p=filter_flow_diagram&g=1

**Comment by cwulfman** [comment]
![Image](https://github.com/htrc/torchlite-app/assets/891097/0ad77a2f-f1e2-451d-9b77-907db9b82f6a)
