### ISSUE TITLE
Dashboard must allow user to select user worksets, HTRC featured worksets, and public worksets

### ISSUE THREAD

**Issue by jchristie01** [htrc/torchlite-app#50]
See these user stories: 

- [As an end user, I want to be able to choose a workset on which to focus my dashboard so that I can use the dashboard to explore the workset](https://github.com/htrc/torchlite-app/issues/14)
- [As an end user, I want to be able to load a workset I have defined into my dashboard](https://github.com/htrc/torchlite-app/issues/15)
- [As an end user, I want to be able to load a pre-defined workset into my dashboard](https://github.com/htrc/torchlite-app/issues/24)

**Comment by jswatsch** [comment]
@dkudeki Is still working on making private worksets available through the dashboard.

**Comment by jswatsch** [comment]
Related to [125](https://github.com/htrc/torchlite-backend/issues/125)

**Comment by gworthey** [comment]
Closed as complete, but with open question re: "My worksets" option in dropdown when user is not logged in. Two competing possibilities:

1. Keep "My worksets" but have it greyed out (possibly prompting user to log in)
2. Remove "My worksets" option altogether.

Leaving this decision for later, pending user testing.
