### ISSUE TITLE
Users should be able to share their work (e.g., url, download file, embed link, etc.)

### ISSUE THREAD

**Issue by jchristie01** [htrc/torchlite-app#61]

**Comment by dkudeki** [comment]
@jchristie01 After our discussion this morning I realized there is a UI component to this that hasn't been discussed at all AFAIK. Basically the frontend needs some way for the user to get the URL to share. Probably a button that either copies the sharable URL to the clipboard, or displays the URL to allow the user to manually copy it. This isn't super urgent, but I wanted to give you a heads up to start thinking about this.

**Comment by jchristie01** [comment]
@dkudeki good catch! For MVP are we thinking widget level, or dashboard level?

**Comment by dkudeki** [comment]
@jchristie01 I've been thinking about it on the dashboard level. Widgets need a dashboard to exist anyway, so that would be the simpler approach for me

**Comment by jswatsch** [comment]
Deren will start after Mutual TLS

**Comment by jswatsch** [comment]
Icon button with pop up shareable link, e.g. like bookworm.

**Comment by gworthey** [comment]
@jchristie01 has created the icon button; other functions still in progress

**Comment by dkudeki** [comment]
Deployed to dev with https://github.com/htrc/torchlite-frontend/pull/145

This still doesn't work with custom stopword lists, though users could share the link and the list. Post-MVP work could be setting up a route like `/dahsboards/[id]/share` which creates a clone on the backend that includes the custom stopword list and pushes that clone to the user.
