### ISSUE TITLE
Set up production instance of TORCHLITE

### ISSUE THREAD

**Issue by jswatsch** [htrc/torchlite-app#72]
- [x] Create client in KeyCloak
- [x] Update secrets in Kubernetes
- [ ]

**Comment by jswatsch** [comment]
Dependent on [88](https://github.com/htrc/torchlite-backend/issues/88)

**Comment by jswatsch** [comment]
Next step: Sandeep, Deren, and Samitha, and Pooja need meeting to discuss what is needed for production instance.

- [ ] Need new config files
- [ ] Decide which EF API to use
- [ ] Is documentation complete? Pooja's documentation mostly has to do with adding a node.
- [ ] set up backups of production instance

**Comment by jswatsch** [comment]
- Currently there are only two labels -- one for dev and one for stage. We need to add one for production in the YAML file.
- Needs to gather all the secrets required for the production instance
- Will then start testing by doing deployment on the main branch

**Comment by jswatsch** [comment]
- Sandeep has gathered the encoded secrets
- Focusing on MongoDB
- Discovered what needs to be done for the ArgoCD to push to production

**Comment by gworthey** [comment]
* Appropriate yaml file and secrets now identified
* MongoDB stuck in "pending" state: 
** command to check: kubectl get mongodbcommunity --namespace torchlite-prod
** Sandeep working on this
** Note that the -dev instance also has a persistent "health checks failing" warning (Deren will work on that)

**Comment by gworthey** [comment]
Samitha set up keycloak instance for -prod stack. All info is in [wiki](https://htrc.atlassian.net/wiki/spaces/SYSADM/pages/25821226/Keycloak+Identity+Provider)

**Comment by jswatsch** [comment]
@sandeep-ps is still investigating why the secrets that are created in the production YAML file are slightly different.
