### ISSUE TITLE
Internal server error in DEV

### ISSUE THREAD

**Issue by jswatsch** [htrc/torchlite-app#79]

**Comment by jswatsch** [comment]
Could be related to a node being down-- and running into a resource constraint.

**Comment by sandeep-ps** [comment]
Hi, @jswatsch, After the morning meeting, @dkudeki informed that the development instance was running one of the feature branches under active development (and not the develop branch). Once he switched development instance to run the develop branch, the errors have gone and now the dashboards are loading just fine. I have also verified this by running different TORCHLITE backend endpoints from Postman. If the currently deployed version looks good to you, I think this issue can be closed. Thanks.

**Comment by jswatsch** [comment]
The error occurred because a different branch was running on dev. The error has been fixed in the other branch.
